In [ ]:
#1.Import the numpy package under the name np
import numpy as np

In [ ]:
#2.Print the numpy version and the configuration
print(np.__version__)

1.21.5


In [ ]:
#3. Create a null vector of size 10
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#4. How to find the memory size of any array
print(x.size)

10


In [ ]:
#5. How to get the documentation of the numpy add function from the command line? 
python -c "import numpy; numpy.info(numpy.add)"

In [ ]:
#6. Create a null vector of size 10 but the fifth value which is 1
x = np.zeros(10)
x[5] = 1
print(x)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [ ]:
#7.Create a vector with values ranging from 10 to 49
y = np.arange(10,49)
print(y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
#8. Reverse a vector (first element becomes last)
y = y[::-1]
print(y)

[48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26 25
 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [ ]:
#9.Create a 3x3 matrix with values ranging from 0 to 8
z=np.arange(0,9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#10.Find indices of non-zero elements from [1,2,0,0,4,0] 
s = np.nonzero([1,2,0,0,4,0])
print(s)

(array([0, 1, 4]),)


In [ ]:
#11.identity matrix
a=np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#12. Create a 3x3x3 array with random values
b = np.random.random((3,3,3))
print(b)

[[[0.79068735 0.49503435 0.05071989]
  [0.14534005 0.77782264 0.97358509]
  [0.61816766 0.17943657 0.24307909]]

 [[0.09539044 0.74963696 0.76977026]
  [0.94123088 0.03510065 0.39877736]
  [0.54285441 0.79590619 0.09082909]]

 [[0.16042999 0.38291582 0.94874758]
  [0.61821125 0.54234624 0.68172787]
  [0.90660484 0.8561516  0.34679565]]]


In [ ]:
#13.Create a 10x10 array with random values and find the minimum and maximum values
random_val = np.random.random((10,10))
print(random_val)
min = random_val.min()
max = random_val.max()
print("min_val:",min)
print("max_val:",max)

[[0.44300607 0.87806427 0.05692472 0.12517911 0.53563411 0.71608296
  0.52338629 0.64020697 0.80136256 0.29156754]
 [0.00147418 0.2911971  0.86536241 0.18507901 0.43782664 0.08854077
  0.00552289 0.85746423 0.71983289 0.87849199]
 [0.83614467 0.59354188 0.58927687 0.18026331 0.38731681 0.79367809
  0.90527608 0.76048743 0.38223369 0.11175798]
 [0.05387022 0.28865016 0.28594383 0.58369014 0.1210655  0.16160931
  0.86762965 0.95986222 0.69596804 0.89724847]
 [0.29758738 0.46529879 0.26307587 0.95527811 0.94519376 0.52486664
  0.01939325 0.08111614 0.51283077 0.34672963]
 [0.39117584 0.37691145 0.956416   0.45901475 0.28114745 0.36087897
  0.57485654 0.8855648  0.01526715 0.34314677]
 [0.36658196 0.69738824 0.62174932 0.52465442 0.64351642 0.58658335
  0.06133948 0.85008774 0.12054162 0.30840547]
 [0.24998501 0.95921794 0.72820482 0.28403099 0.35494932 0.62084681
  0.89131844 0.7337084  0.06122509 0.46574662]
 [0.15170887 0.81368891 0.25818491 0.68826684 0.31682685 0.17728961
  0.40985014

In [ ]:
#14. Create a random vector of size 30 and find the mean value
c = np.random.random(30)
print(c)
c = np.mean(c)
print("mean:",c)

[0.59421784 0.72280768 0.98073773 0.55067021 0.44197688 0.01841121
 0.36333147 0.73087835 0.4299266  0.21531032 0.24439604 0.95334683
 0.63955067 0.37524257 0.57376027 0.64877683 0.07766865 0.50892712
 0.49756376 0.78442652 0.8406987  0.03761601 0.8531643  0.14466137
 0.16990861 0.03303853 0.27913616 0.62227128 0.83917017 0.54455192]
mean: 0.490538151919495


In [ ]:
#15. Create a 2d array with 1 on the border and 0 inside 
d_array = np.ones((5,5))
d_array[1:-1,1:-1] = 0
print(d_array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
#16. How to add a border (filled with 0's) around an existing array?
e=np.ones((5,5))

e=np.pad(e, pad_width= 1, mode='constant', constant_values=0)
print(e)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#What is the result of the following expression? 
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [ ]:
#18.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
#19.Create a 8x8 matrix and fill it with a checkerboard pattern
mat = np.ones((3,3))
mat = np.zeros((8,8),dtype =int)
mat[1::2,::2] = 1
mat[::2,1::2] = 1
print(mat)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [ ]:
#21. Create a checkerboard 8x8 matrix using the tile function 
chk_board_mat = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(chk_board_mat)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#22. Normalize a 5x5 random matrix
rdm_mat = np.random.random((5,5))
rdm_mat = (rdm_mat - np.mean(rdm_mat))/(np.std(rdm_mat))
print(rdm_mat)

[[ 1.64935605  1.41066676  0.81909603 -0.614702   -1.35146602]
 [ 0.55878955 -0.35679508  1.28532082 -1.38261887 -1.07237406]
 [-0.93667558 -1.01329688 -1.3582824  -0.21608651  0.94880437]
 [-0.29486678  0.32045199 -1.41660055 -0.01636887 -0.37385403]
 [ 0.11757071 -0.1350988   0.92175634  2.0294763   0.47779752]]


In [ ]:
#23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)
color = np.dtype([("r", np.ubyte),("g", np.ubyte),("b", np.ubyte),("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [ ]:
#24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
a = np.ones((5,3))
b = np.ones((3,2))
c = np.dot(a,b)
#or
c = a @ b
print(c)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [ ]:
#25.Given a 1D array, negate all elements which are between 3 and 8, in place. 
Z=np.arange(11)

Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [ ]:
#26.What is the output of the following script? 
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
#27. Consider an integer vector Z, which of these expressions are legal?
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

In [ ]:
#28. What are the result of the following expressions?
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([-9.22337204e+18])

In [ ]:
#29. How to round away from zero a float array ?
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

[ 1.  6. -2.  9.  2.  1.  4.  7.  8. -8.]
[ 1.  6. -2.  9.  2.  1.  4.  7.  8. -8.]


In [ ]:
#30. How to find common values between two arrays?
a1=np.random.randint(0,10,10)
a2=np.random.randint(0,10,10)
print(np.intersect1d(a1,a2))

[0 2 6]


In [ ]:
#31. How to ignore all numpy warnings (not recommended)? 

In [ ]:
#32. Is the following expressions true? 
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


In [ ]:
#33. How to get the dates of yesterday, today and tomorrow?

yesterday=np.datetime64('today')-np.timedelta64(1)
Today=np.datetime64('today')
Tomorrow=np.datetime64('today')+np.timedelta64(1)
print(yesterday,Today,Tomorrow)

2022-02-18 2022-02-19 2022-02-20


In [ ]:
#34. How to get all the dates corresponding to the month of July 2016?
c = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(c)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
#35. How to compute ((A+B)*(-A/2)) in place (without copy)?
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [ ]:
#36. Extract the integer part of a random array using 5 different methods 
a=np.random.uniform(0,10,5)#np.random.uniform(low,high,size)
print(a-a%1)
print(a//1)
print(np.floor(a))
print(a.astype(int))
print(np.trunc(a))


[0. 7. 0. 9. 1.]
[0. 7. 0. 9. 1.]
[0. 7. 0. 9. 1.]
[0 7 0 9 1]
[0. 7. 0. 9. 1.]


In [ ]:
#37.Create a 5x5 matrix with row values ranging from 0 to 4
a=np.zeros((5,5))
a +=np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
#38. Consider a generator function that generates 10 integers and use it to build an array 
def generate():
  for x in range(10):
    yield x
a = np.fromiter(generate(),dtype=float,count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
#39. Create a vector of size 10 with values ranging from 0 to 1, both excluded
np.linspace(0,1,11,endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [ ]:
#40. Create a random vector of size 10 and sort it 
c=np.random.random(10)
c.sort()
c

array([0.25963669, 0.33887039, 0.35428975, 0.40464824, 0.41073605,
       0.62103638, 0.63503483, 0.69389891, 0.84175695, 0.98800413])

In [ ]:
#41. How to sum a small array faster than np.sum? 
a=np.arange(10)
np.add.reduce(a)

45

In [ ]:
#42. Consider two random array A and B, check if they are equal
A=np.random.randint(0,2,5)
B=np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)

False


In [ ]:
#43. Make an array immutable (read-only)
a=np.zeros(10)
a.flags.writeable=False


In [ ]:
#44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates
a=np.random.random((10,2))
a
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

array([[0.30921012, 0.16934021],
       [0.37227925, 0.3519324 ],
       [0.1470981 , 0.70695528],
       [0.96713604, 0.49955795],
       [0.46465865, 0.15293731],
       [0.14333691, 0.65451653],
       [0.0574587 , 0.83127655],
       [0.80481757, 0.79603397],
       [0.27216244, 0.54638195],
       [0.34397884, 0.10114297]])

In [ ]:
#45. Create random vector of size 10 and replace the maximum value by 0
a = np.random.random(10)
a[a.argmax()] = 0
print(a)

[0.14613395 0.96131576 0.66903122 0.82759377 0.12749024 0.93979402
 0.30951108 0.54783849 0.20289018 0.        ]


In [ ]:
#46. Create a structured array with x and y coordinates covering the [0,1]x[0,1] area 
a = np.zeros((5,5), [('b',float),('c',float)])
a['b'], a['c'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(a)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [ ]:
#47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
a = np.arange(8)
b = a + 0.5
C = 1.0 / np.subtract.outer(a, b)
print(np.linalg.det(C))

3638.163637117973


In [ ]:
#48. Print the minimum and maximum representable value for each numpy scalar type
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [ ]:
#49. How to print all the values of an array?
np.set_printoptions(threshold=float("inf"))
b = np.zeros((10,10))
print(b)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#50. How to find the closest value (to a given scalar) in a vector? 
x = np.arange(100)

a = np.random.uniform(0,100)

index = (np.abs(x-a)).argmin()
print(x[index])

80


In [ ]:
#51.Create a structured array representing a position (x,y) and a color (r,g,b)
a = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 2)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 2),
                                   ('b', float, 3)])])
print(a)

[((0., [0., 0.]), (0., [0., 0.], [0., 0., 0.]))
 ((0., [0., 0.]), (0., [0., 0.], [0., 0., 0.]))
 ((0., [0., 0.]), (0., [0., 0.], [0., 0., 0.]))
 ((0., [0., 0.]), (0., [0., 0.], [0., 0., 0.]))
 ((0., [0., 0.]), (0., [0., 0.], [0., 0., 0.]))
 ((0., [0., 0.]), (0., [0., 0.], [0., 0., 0.]))
 ((0., [0., 0.]), (0., [0., 0.], [0., 0., 0.]))
 ((0., [0., 0.]), (0., [0., 0.], [0., 0., 0.]))
 ((0., [0., 0.]), (0., [0., 0.], [0., 0., 0.]))
 ((0., [0., 0.]), (0., [0., 0.], [0., 0., 0.]))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  


In [ ]:
#52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0]), np.atleast_2d(Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)


import scipy

import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.22221928 0.73788956 0.74932129 0.75653087 0.85948013
  0.67606673 0.57280394 0.90305363 0.4362161 ]
 [0.22221928 0.         0.62960732 0.58904158 0.55746846 0.78638194
  0.73476851 0.3546565  0.98484658 0.37345714]
 [0.73788956 0.62960732 0.         0.19946773 0.3949826  0.19135785
  0.52606333 0.51794095 0.73689164 0.30727657]
 [0.74932129 0.58904158 0.19946773 0.         0.19965223 0.37796518
  0.70263782 0.3722979  0.92783678 0.37770187]
 [0.75653087 0.55746846 0.3949826  0.19965223 0.         0.57753095
  0.86483367 0.24203601 1.10310516 0.48187155]
 [0.85948013 0.78638194 0.19135785 0.37796518 0.57753095 0.
  0.46746433 0.70867271 0.62643068 0.4262885 ]
 [0.67606673 0.73476851 0.52606333 0.70263782 0.86483367 0.46746433
  0.         0.86896808 0.25658915 0.42363213]
 [0.57280394 0.3546565  0.51794095 0.3722979  0.24203601 0.70867271
  0.86896808 0.         1.12327709 0.44604429]
 [0.90305363 0.98484658 0.73689164 0.92783678 1.10310516 0.62643068
  0.25658915 1.12327

In [ ]:
#53.How to convert a float (32 bits) array into an integer (32 bits) in place?
a = np.arange(10, dtype=np.int32)
a = a.astype(np.float32, copy=False)
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [ ]:
#54. How to read the following file?
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
Z = np.genfromtxt("missing.dat", delimiter=",")


In [ ]:
#55. What is the equivalent of enumerate for numpy arrays?
b = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(b):
    print(index, value)
for index in np.ndindex(b.shape):
    print(index, b[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [ ]:
#56. Generate a generic 2D Gaussian-like array
x,y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [ ]:
#57. How to randomly place p elements in a 2D array? 
n = 10
p = 9
e = np.zeros((n,n))
np.put(e, np.random.choice(range(n*n), p, replace=False),1)
print(e)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#58. Subtract the mean of each row of a matrix
a=np.random.rand(5,7)
b = b - b.mean(axis=1, keepdims=True)
b

array([[-1.,  0.,  1.],
       [-1.,  0.,  1.],
       [-1.,  0.,  1.]])

In [ ]:
#59. How to sort an array by the nth column? 
a = np.random.randint(0,5,(4,4))
print(a)
print(a[a[:,1].argsort()])

[[2 1 4 1]
 [3 2 4 2]
 [2 4 4 1]
 [0 2 3 1]]
[[2 1 4 1]
 [3 2 4 2]
 [0 2 3 1]
 [2 4 4 1]]


In [ ]:
#60. How to tell if a given 2D array has null columns?
a = np.random.randint(0,3,(3,3))
print((~a.any(axis=0)).any())

False


In [ ]:
#61. Find the nearest value from a given value in an array 
a = np.random.uniform(0,1,5)
b = 0.5
m = a.flat[np.abs(a - b).argmin()]
print(m)

0.4658126680557123


In [ ]:
#62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:
#63. Create an array class that has a name attribute
class name_arr(np.ndarray):
  def __new__(cls,array,name="no name"):
      obj = np.asarray(array).view(cls)
      obj.name = name
      return obj
  def __array_finalize__(self, obj):
      if obj is None: return
      self.info = getattr(obj, 'name', "no name")
Z = name_arr(np.arange(10), "range_10")
print (Z.name)

range_10


In [ ]:
#64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?
B = np.ones(10)
C = np.random.randint(0,len(B),20)
np.add.at(B, C, 1)
print(Z)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
#65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? 
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [ ]:
#66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors
w, h = 200, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)


64


In [ ]:
#67. Considering a four dimensions array, how to get sum over the last two axis at once? 
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)

[[43 48 50 64]
 [56 52 58 66]
 [59 48 65 48]]


In [ ]:
#68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset indices?
D = np.random.uniform(0,1,50)
S = np.random.randint(0,10,50)
D_sum = np.bincount(S, weights=D)
D_count = np.bincount(S)
D_mean = D_sum / D_count
print(D_mean)

[0.66741929 0.55562707 0.37802091 0.62697899 0.39700444 0.62981394
 0.59478318 0.45154593 0.33828899 0.48679343]


In [ ]:
#69. How to get the diagonal of a dot product?
A = np.random.uniform(0,1,(4,4))
B = np.random.uniform(0,1,(4,4))
np.sum(A * B.T, axis=1)

array([0.11349827, 1.21001262, 1.71666411, 0.34475691])

In [ ]:
#70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


In [ ]:
#71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)?
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


In [ ]:
#72. How to swap two rows of an array?
B = np.arange(25).reshape(5,5)
B[[0,1]] = B[[1,0]]
print(B)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
#73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the triangles 
faces = np.random.randint(0,100,(10,3))
f = np.roll(faces.repeat(2,axis=1),-1,axis=1)
f = F.reshape(len(f)*3,2)
f = np.sort(f,axis=1)
G = f.view( dtype=[('p0',f.dtype),('p1',f.dtype)] )
G = np.unique(G)
print(G)

[( 0, 20) ( 0, 42) ( 5, 85) ( 5, 91) ( 9, 18) ( 9, 62) (10, 30) (10, 67)
 (11, 19) (11, 63) (14, 51) (14, 99) (18, 19) (18, 62) (18, 94) (19, 63)
 (19, 77) (19, 94) (19, 96) (20, 42) (21, 51) (21, 92) (30, 67) (51, 92)
 (51, 99) (58, 75) (58, 90) (75, 90) (77, 96) (85, 91)]


In [ ]:
#74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? 
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


In [ ]:
#75. How to compute averages using a sliding window over an array? 
from numpy.lib.stride_tricks import sliding_window_view
Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [ ]:
#76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1])
Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
#77. How to negate a boolean, or to change the sign of a float inplace?
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.41215926, -0.50560498, -0.03853318, -0.26627853, -0.17481141,
        0.67010389,  0.67247188,  0.03130057, -0.70920829, -0.11950305,
        0.09617326, -0.20422593,  0.47545559,  0.91508462, -0.4268526 ,
        0.24423094, -0.42512063, -0.61881179, -0.98359883,  0.18974886,
       -0.72696628,  0.00770053, -0.64699292, -0.17722491,  0.3605433 ,
        0.3039466 , -0.14493983, -0.68221637, -0.99548587, -0.37132367,
        0.93733042, -0.02543925,  0.36282978,  0.87576071,  0.04691622,
        0.30898754, -0.84237417, -0.30041727, -0.61895746,  0.8478783 ,
        0.4631858 ,  0.79730422, -0.54934773, -0.191083  , -0.27668723,
       -0.47502832,  0.15112509, -0.86707514,  0.71663135,  0.51076175,
        0.49367118,  0.92113419,  0.06130875,  0.59680618,  0.82028537,
        0.96922676,  0.96449676,  0.57278926, -0.91650105,  0.51919926,
       -0.06915096,  0.24669791,  0.17229722, -0.2305538 ,  0.95207286,
       -0.57412663,  0.79862602, -0.61792198,  0.4168146 ,  0.71

In [ ]:
#78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])?
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[13.7603514   8.57819819  8.66735786  3.51934139  2.22472858 11.73878252
 12.8181284  10.92226555  2.91822921  2.12113835]


In [ ]:
#79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])?
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[8.73512219e+00 7.56792990e+00 5.08903540e+00 7.82281038e+00
  7.85538707e+00 7.83765251e+00 7.19712200e+00 3.22451970e+00
  4.19386350e+00 9.03145041e-01]
 [3.71189725e+00 8.69798426e+00 2.00152983e+00 1.12156954e+00
  1.03043308e+01 3.26163465e-01 6.33681446e+00 7.54631301e-01
  3.29575161e+00 3.22205597e+00]
 [4.74944962e+00 1.94114288e+01 8.55237421e-01 5.32076261e+00
  2.06814426e+01 2.60899983e-01 1.69092139e+01 1.02373565e+01
  3.19050633e+00 6.75598599e+00]
 [5.70833963e+00 7.59634615e+00 2.79631701e-01 2.63787845e+00
  8.86796299e+00 2.41790782e+00 5.78836287e+00 1.03275702e+00
  1.26124771e+00 3.32874860e+00]
 [1.15074345e+01 2.50342210e+00 1.54183727e+00 3.71463400e+00
  3.35236430e+00 5.90129955e+00 1.61221250e+00 6.82195880e+00
  1.91503817e+00 6.62192586e+00]
 [3.56236521e+00 8.63058374e+00 2.38234732e+00 7.44466618e-01
  1.03055278e+01 3.58189302e-02 6.17333097e+00 8.41198957e-01
  3.66460030e+00 3.45032110e+00]
 [8.35273899e+00 5.15062607e+00 3.43760744e-01 2.91206743e

In [ ]:
#80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a fill value when necessary)
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)
R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2
R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[0 0 7 1 7 2 0 3 4 0]
 [8 3 2 5 4 2 9 0 4 0]
 [3 4 9 7 4 9 4 9 9 5]
 [6 4 5 3 9 6 7 9 7 9]
 [2 9 4 8 6 3 6 1 6 2]
 [8 3 6 0 5 1 1 5 4 4]
 [4 3 7 3 4 8 6 0 9 1]
 [2 0 6 4 5 8 6 9 6 3]
 [2 2 0 1 0 4 1 0 2 6]
 [1 2 0 2 1 8 6 9 3 2]]
[[0 0 0 0 0]
 [0 0 0 7 1]
 [0 8 3 2 5]
 [0 3 4 9 7]
 [0 6 4 5 3]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:20: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [ ]:
#81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?
from numpy.lib.stride_tricks import sliding_window_view
Z= np.arange(1,15,dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [ ]:
#82. Compute a matrix rank
Z = np.random.uniform(0,1,(10,10))
Z
U, S, V = np.linalg.svd(Z) 
rank = np.sum(S > 1e-10)
print(rank)

10


In [ ]:
#83. How to find the most frequent value in an array?
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

5


In [ ]:
#84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix
from numpy.lib.stride_tricks import sliding_window_view
Z = np.random.randint(0,5,(4,4))
print(sliding_window_view(Z, window_shape=(3, 3)))


[[[[4 3 2]
   [1 3 0]
   [1 3 3]]

  [[3 2 0]
   [3 0 1]
   [3 3 4]]]


 [[[1 3 0]
   [1 3 3]
   [1 2 0]]

  [[3 0 1]
   [3 3 4]
   [2 0 4]]]]


In [ ]:
#85. Create a 2D array subclass such that Z[i,j] == Z[j,i]
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5  7  9  7 16]
 [ 7  6  8 10 14]
 [ 9  8  3 42  2]
 [ 7 10 42  6  7]
 [16 14  2  7  0]]


In [ ]:
#86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) 
p, n = 10, 10
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]
 [100.]]


In [ ]:
#87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? 
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [ ]:
#88. How to implement the Game of Life using numpy arrays? 
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])


    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
#89. How to get the n largest values of an array 
Z = np.arange(10000)
print (Z[np.argsort(Z)[-n:]])

[9990 9991 9992 9993 9994 9995 9996 9997 9998 9999]


In [ ]:
#90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) 
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


In [ ]:
#91. How to create a record array from a regular array?
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


In [ ]:
#92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods 
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1 loop, best of 5: 3.4 s per loop
10 loops, best of 5: 188 ms per loop
10 loops, best of 5: 148 ms per loop


In [ ]:
#93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? 
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[3 4 5 7]


In [ ]:
#94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3])
Z = np.random.randint(0,5,(10,3))
print(Z)

E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 1 0]
 [0 3 1]
 [4 3 2]
 [4 4 1]
 [4 4 2]
 [2 2 2]
 [2 4 2]
 [2 4 0]
 [0 0 2]
 [3 1 1]]
[[4 1 0]
 [0 3 1]
 [4 3 2]
 [4 4 1]
 [4 4 2]
 [2 4 2]
 [2 4 0]
 [0 0 2]
 [3 1 1]]
[[4 1 0]
 [0 3 1]
 [4 3 2]
 [4 4 1]
 [4 4 2]
 [2 4 2]
 [2 4 0]
 [0 0 2]
 [3 1 1]]


In [ ]:
#95. Convert a vector of ints into a matrix binary representation 
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [ ]:
#96. Given a two dimensional array, how to extract unique rows?
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [1 1 1]]


In [ ]:
#97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)

array([[0.10902724, 0.08009177, 0.00122559, 0.09054429, 0.03924136,
        0.09260101, 0.0304984 , 0.06481906, 0.02142742, 0.03523871],
       [0.32290974, 0.23721057, 0.00362986, 0.26816815, 0.11622249,
        0.27425962, 0.09032816, 0.19197686, 0.06346232, 0.10436771],
       [0.07347689, 0.05397637, 0.00082596, 0.06102065, 0.02644599,
        0.06240674, 0.02055383, 0.04368361, 0.01444061, 0.02374848],
       [0.61938044, 0.45499893, 0.00696251, 0.51437937, 0.22292897,
        0.52606355, 0.17326049, 0.36823514, 0.12172851, 0.20019005],
       [0.65689408, 0.48255658, 0.00738421, 0.54553347, 0.23643097,
        0.55792532, 0.18375425, 0.39053781, 0.12910117, 0.21231484],
       [0.48390004, 0.35547458, 0.00543957, 0.40186641, 0.17416652,
        0.41099485, 0.13536229, 0.28768909, 0.09510218, 0.15640141],
       [0.65474468, 0.48097762, 0.00736005, 0.54374845, 0.23565735,
        0.55609976, 0.18315299, 0.38925995, 0.12867874, 0.21162014],
       [0.31372373, 0.2304625 , 0.0035266

In [ ]:
#98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

In [ ]:
#99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n.
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


In [ ]:
#100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). 
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.14439366  0.29304958]
